# Generated by Django 4.1.7 on 2023-02-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0002_alter_task_options_alter_task_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=150, unique=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'task_post_list_model_table',
                'ordering': ('id',),
            },
        ),
    ]
