# Generated by Django 4.1.7 on 2023-03-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_alter_postmodel_options_alter_postmodel_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='Заголовок'),
        ),
    ]
